spring:
  application:
    name: config-client
  profiles:
    active: development
  config:
#    import: "optional:configserver:http://user:secret1234@localhost:8888"
    import: "optional:configserver:http://localhost:8888"
  rbbitmq:
    host: localhost
    port:  5672
  cloud:
    config:
      label: 1.0.1

management:
  endpoints:
    web:
      exposure:
        include: "refresh,busrefresh"
encrypt:
  key-store:
    location: classpath:/config-private.jks
    alias: config-private-key
    password: pass1234
    secret: pass1234

app:
  name: local
  config:
    name: local
    password: local-password
