logging:
  level:
    'jhkim105.tutorials': debug

spring:
  datasource:
    url: 'jdbc:h2:mem:demo;DB_CLOSE_ON_EXIT=FALSE'
    username: sa
  h2:
    console.enabled: true
  jpa:
    hibernate.ddl-auto: create