server:
  port: 8081
spring:
  application:
    name: book
  config:
    import: "optional:configserver:http://localhost:8888"
  datasource:
    url: jdbc:mariadb://localhost/demo_svc_book?createDatabaseIfNotExist=true
    username: root
    password: 111111
  sql:
    init:
      mode: always
      continue-on-error: false
  jpa:
    "defer-datasource-initialization": true
    "hibernate.ddl-auto": create
    properties:
      "hibernate.id.new_generator_mappings": false
logging:
  level:
    "jhkim105.tutorials": debug