# LOGGING
logging:
  level:
    com.example.demo: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.EnumType: trace
    org.springframework.transaction: debug

spring:
  # DB - MySQL
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://@db.address@/@db.name@?createDatabaseIfNotExist=true
    username: @db.username@
    password: @db.password@
  #    driver-class-name: org.mariadb.jdbc.Driver

  sql:
    init:
      mode: always
      #      data-locations: data.sql
      continue-on-error: false

  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create

