server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/jihwankim/dev/my/tutorials/spring-cloud-config/config-server/conf