server:
  port: 8888
spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/config-repo
          default-label: main
#        native:
#          search-locations: file:///Users/jihwankim/dev/my/tutorials/spring-cloud-config/config-server/conf