spring:
  profiles:
    default: local
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mariadb://localhost/demo_flyway?createDatabaseIfNotExist=true
    username: root
    password: 111111
  jpa:
    hibernate:
      ddl-auto: create
  flyway:
    enabled: false
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mariadb://localhost/demo_flyway_test?createDatabaseIfNotExist=true
    username: root
    password: 111111
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: false
---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:mariadb://localhost/demo_flyway_real?createDatabaseIfNotExist=true
    username: root
    password: 111111
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/callback
    baseline-on-migrate: true
    baseline-version: 0