# grant_type=password
# curl -X POST http://localhost:8081/oauth/token -u "client01:secret01" -H "Content-type: application/x-www-form-urlencoded" -d grant_type=password -d scope=read -d username=user01 -d password=pass01
POST http://localhost:8081/oauth/token
Authorization: Basic client01 secret01
Content-Type: application/x-www-form-urlencoded

grant_type=password&scope=read&username=user01&password=pass01
###

# grant_type=client_credentials
# curl "http://localhost:8081/oauth/token" -u "client01:secret01" -d "grant_type=client_credentials&scope=read"
POST http://localhost:8081/oauth/token
Authorization: Basic client01 secret01
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=read
###


# grant_type=authorization_code
# http://localhost:8081/oauth/authorize?response_type=code&client_id=client01&redirect_uri=http://localhost:8080/authorization-code&scope=read
# -> http://localhost:8080/authorization-code?code=DG67dc
# curl http://localhost:8081/oauth/token -u "client01:secret01" -d "grant_type=authorization_code" -d "code=XksyWp" -d "redirect_uri=http://localhost:8080/authorization-code" -d "scope=read"
POST http://localhost:8081/oauth/token
Authorization: Basic client01 secret01
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code&code=XksyWp&redirect_uri=http://localhost:8080/authorization-code&scope=read

###


