logging:
  level:
    root: info
    'jhkim105.tutorials': debug
    'org.hibernate.SQL': debug
    'org.hibernate.type.descriptor.sql.BasicBinder': trace
    'org.hibernate.type.EnumType': trace
    'org.springframework.transaction': trace
    'org.springframework.orm.jpa': debug
    'org.springframework.jdbc.core': trace
spring:
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate.hbm2ddl.auto: create
      hibernate.physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
#    open-in-view: false
  sql:
    init:
      mode: always
multitenancy:
  master:
    datasource:
      url: jdbc:mariadb://@db.address@/@db.name@?createDatabaseIfNotExist=true
      username: @db.username@
      password: @db.password@
      driver-class-name: org.mariadb.jdbc.Driver
      dbcp2:
        max-total: 20
        initial-size: 20
        max-idle: 20
        min-idle: 10
  tenant:
    datasource:
      address: @db.address@
      username: @db.username@
      password: @db.password@