logging:
  level:
    root: info
    'jhkim105.tutorials': debug
    'org.hibernate.SQL': debug
    'org.hibernate.type.descriptor.sql.BasicBinder': trace
    'org.hibernate.type.EnumType': trace
    'org.springframework.transaction': trace
    'org.springframework.orm.jpa': debug
    'org.springframework.jdbc.core': trace
    'org.springframework.orm.jpa.support': debug
spring:
  jpa:
    properties:
      hibernate.hbm2ddl.auto: validate
      hibernate.physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mariadb://@db.address@/@db.name@?createDatabaseIfNotExist=true
    username: @db.username@
    password: @db.password@
    driver-class-name: org.mariadb.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      max-total: 20
      initial-size: 10
      max-idle: 10
      min-idle: 10
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0


tenant:
  datasource:
    address: @db.address@
    username: @db.username@
    password: @db.password@
  datasource-cache:
    max-size: 100
    expire-minutes: 1
  flyway:
    migrate-on-server-start: true
    migrate-on-tenant-add: true
    locations: classpath:db/migration_tenant
    baseline-version: 0.0.1