logging:
  level:
    root: info
    'jhkim105.tutorials': debug
    'org.hibernate.SQL': debug
    'org.hibernate.type.descriptor.sql.BasicBinder': trace
    'org.hibernate.type.EnumType': trace
    'org.springframework.transaction': trace
    'org.springframework.orm.jpa': debug
    'org.springframework.jdbc.core': trace
    'org.springframework.orm.jpa.support': debug
spring:
  jpa:
    properties:
      hibernate.hbm2ddl.auto: create
      hibernate.physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      hibernate.id.new_generator_mappings: false
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:mariadb://@db.address@/@db.name@?createDatabaseIfNotExist=true
    username: @db.username@
    password: @db.password@
    driver-class-name: org.mariadb.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      max-total: 20
      initial-size: 10
      max-idle: 10
      min-idle: 10
  flyway:
    enabled: false

tenant:
    datasource:
      address: @db.address@
      username: @db.username@
      password: @db.password@
    datasource-cache:
      max-size: 100
      expire-minutes: 1
    flyway:
      migrate-on-server-start: false
      migrate-on-tenant-add: false
      locations: classpath:db/migration_tenant