spring:
  application:
    name: config-client
  profiles:
    active: development
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: "http://localhost:8888"
#      fail-fast: true
      enabled: false


