logging:
  level:
    root: info
    com.example.demo: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.EnumType: trace

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jpa:
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create
    properties:
      hibernate.hbm2ddl.auto: create
      hibernate.physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

user:
  datasource:
    url: jdbc:mariadb://localhost/demo_mds_user?createDatabaseIfNotExist=true
    username: root
    password: @db.password@
    dbcp2:
      max-total: 20
      initial-size: 20
      max-idle: 20
      min-idle: 10

product:
  datasource:
    url: jdbc:mariadb://localhost/demo_mds_product?createDatabaseIfNotExist=true
    username: root # not replaced
    password: @db.password@
    dbcp2:
      max-total: 20
      initial-size: 20
      max-idle: 20
      min-idle: 10


