logging:
  level:
    root: debug
    com.example: debug

spring:
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:demo
    sql-script-encoding: UTF-8
    initialization-mode: always
    continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: create


