spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: one
          uri: http://localhost:7777
          predicates:
            - Path=/one
        - id: request_filter_get
          uri: https://httpbin.org
          predicates:
            - Path=/request_filter/**
            - Method=GET
          filters:
            - SetPath=/get
            - AddRequestHeader=My-Header-Good,Good
            - AddRequestParameter=var, good
            - MapRequestHeader=My-Header-Good, My-Header-Bad
            - MapRequestHeader=My-Header-Set, My-Header-Bad
            - SetRequestHeader=My-Header-Set, Set
        - id: response_filter_post
          uri: https://httpbin.org
          predicates:
            - Path=/response_filter/**
            - Method=GET
          filters:
            - SetPath=/get
            - AddResponseHeader=My-Header-Good,Good
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - SetResponseHeader=My-Header-Set, Set
            - RemoveResponseHeader=My-Header-Remove
            - RewriteResponseHeader=My-Header-Rewrite, password=[^&]+, password=***
            - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, ,-
        - id: custom_filter
          uri: https://httpbin.org
          predicates:
            - Path=/custom_filter/**
            - Method=GET
          filters:
            - SetPath=/get
            - Logging=Custom Message, true, true

logging:
  level:
    org.springframework.cloud.gateway: trace