server:
  port: 8888

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:@project.basedir@/config
        encrypt:
          enabled: false
  #spring:
#  profiles:
#    active: git
#  cloud:
#    config:
#      server:
#        git:
#          uri: file://${user.home}/config-repo
#          default-label: main

#spring:
#  profiles:
#    active: git
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/jhkim105/config-repo.git
#          username:
#          password:
#  security:
#    user:
#      password: secret1234
encrypt:
  key-store:
    location: classpath:/config-public.jks
    alias: config-public-key
    password: 1234pass
    secret: 1234pass