:hardbreaks:
= Spring Cloud Config Example

== Config Server
Config 저장소로 Git, File, DB 등을 지원함.

=== Config Server - File
pom.xml
[source,xml]
----
	<properties>
		<java.version>11</java.version>
		<spring-cloud.version>2020.0.4</spring-cloud.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-config-server</artifactId>
		</dependency>
	</dependencies>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
----

@EnableConfigServer
[source,java]
----
@SpringBootApplication
@EnableConfigServer
public class ConfigServerApplication {
----

[source,yaml]
----
server:
  port: 8888
spring:
  profiles:
    active: native
----

config/config-client-development.yml
[source,yaml]
----
config.name: service-development
----

http://localhost:8888/config-client/development

Config 위치 지정
지정하게 되면 classpath 에 있는 config 는 무시된다.
classpath 에 config directory 가 없으면 search-locations 설정된 프로퍼티가 로드되지 않는다. 버그로 보임. (2022/03/28)
[source,yaml]
----
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/jihwankim/dev/my/tutorials/spring-cloud/spring-cloud-config/config-server/conf
----

==  Config Client


pom.xml
[source,xml]
----
  <properties>
    <java.version>11</java.version>
    <spring-cloud.version>2020.0.4</spring-cloud.version>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-config</artifactId>
    </dependency>

  </dependencies>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>${spring-cloud.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
----

application.yml
[source,yaml]
----
spring:
  application:
    name: config-client # config file 명과 동일해야 함
  profiles:
    active: development
  config:
    import: "optional:configserver:http://localhost:8888"
management:
  endpoints:
    web:
      exposure:
        include: "refresh"
----

== Config 갱신하기
두가지 방법이 있다
- @RefreshScope with Actuator
- Spring Cloud Bus

=== Refresh - @RefreshScope
Config Client 수정
pom.xml
[source,xml]
----
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
----

@RefreshScope 지정
[source,java]
----
@RestController
@RefreshScope
public class HomeController {


  @Value("${config.name}")
  private String configName;


  @GetMapping("/")
  public String home() {
    return configName;
  }
}
----


갱신하기
[source,shell script]
----
curl -X POST localhost:8080/actuator/refresh
----

=== Refresh - Spring Cloud Bus
Config Client 수정
pom.xml
[source,xml]
----
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-bus-amqp</artifactId>
    </dependency>
----

application.yml
[source,yaml]
----
spring:
  application:
    name: config-client # config file 명과 동일해야 함
  profiles:
    active: development
  config:
    import: "optional:configserver:http://localhost:8888"
  rbbitmq:
    host: localhost
    port:  5672
management:
  endpoints:
    web:
      exposure:
        include: "refresh,busrefresh"
----

갱신하기 - client 한대만 요청하면 전체 client 에 적용됨.
[source,shell script]
----
curl -X POST localhost:8080/actuator/busrefresh
----


== Environment Repository

=== Git Backend
==== git local
[source,yaml]
----
server:
  port: 8888
spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/config-repo
          default-label: main
----

[source,shell script]
----
cd $HOME
mkdir config-repo
cd config-repo
git init .
echo config.name=git-local-config-client-development > config-client-development.properties
git add -A .
git commit -m ‘add'
----

curl http://localhost:8888/config-client/development/main
[source,json]
----
{"name":"config-client","profiles":["development"],"label":"main","version":"a286e0f76e05f89c695edc9ec7f6b11e3d81ec5b","state":null,"propertySources":[{"name":"file:///Users/jihwankim/config-repo/config-client-development.properties","source":{"config.name":"git-local-config-client-development"}}]}
----

config client 에서 label 지정
----
spring.cloud.config.label=1.0.1
----

==== Git - remote
[source,yaml]
----
spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jhkim105/config-repo.git
          username: xxxx
          password: yyyy
----

== Security
Spring Security HTTP Basic Authentication 사용

== Encryption

=== Symmetric

대칭키

application.yml 에 encrypt.key 를 지정하거나, System Property ECRYPT_KEY= 로 지정
Config Server 에서 /encrypt, /decrypt 를 제공함

----
(base) ➜  tutorials git:(master) ✗ curl -X POST http://localhost:8888/encrypt -d 1234
40fc12a9cd56c0f3a85b3716b27af3fa9e88950253732c4f8c860dfaec337024%
----

property
----
  password: '{cipher}40fc12a9cd56c0f3a85b3716b27af3fa9e88950253732c4f8c860dfaec337024'
----

서버쪽에서 암호화 하고 클라이언트에서 복호화하려면 서버쪽에 spring.cloud.config.server.encrypt.enabled=false 설정하고 클라이언트에 encrypt.key 를 설정해야 한다.


=== Asymmetric

keystore 생성 (config-server/src/main/resources)
[source, shell]
----
keytool -genkeypair -alias config-server-key -keyalg RSA \
        -keypass pass1234 -keystore config-server.jks -storepass pass1234 \
        -dname 'CN=Config Server,OU=Spring Cloud,O=Jhkim105'
----

config-server/application.yml

[source, yaml]
----
encrypt:
  key-store:
    location: classpath:/config-server.jks
    alias: config-server-key
    password: pass1234
    secret: pass1234
----

----
(base) ➜  resources git:(master) ✗ curl localhost:8888/encrypt -d 1234 -X POST
AQA66PiKBz1mMXgZsnL/S9wPGsSRBRVAHKVNdzl+Jj+hLLExCeod4nrqQSs2WR3l26/dFzSuCQKjfZ6fT0HylYmMFZfe47rYyis1j5+bBBkfsNmEAUpe9vyLZ2AbqpgmYfPUiRY+U9ONDWPKH/+jYp0fz/rKediOXkmcFQ6lhcnF9Y8l5DMpH4doratccVy4f5XAJprJja5/ClReZNWVmfzlhNu4uQcpkdyiHBBJLippt0wue6EvzZkI5axN1lbOaANQ+UP2dwc2l/FCXfMadpU1R5tZUe/hC7Y9n2uWjUftbkKG0tILV4X4wvbcSBRGQxODUX0rZgUpfjw//VItKSjwlEUukBkSxk80DDIIs2QigzC3XHfsPDvOxcBshpLXFJQ=%
----

==== Server Encrypt and Client Decrypt

* Private Key 생성
----
keytool -genkeypair -alias config-private-key -keyalg RSA \
-keypass pass1234 -keystore config-private.jks -storepass pass1234 \
-dname 'CN=Config Server,OU=Spring Cloud,O=Jhkim105'
----

* 인증서 생성 ( from Private Key)
----
keytool -export -alias config-private-key -keystore config-private.jks -rfc -file config-public.cer
----

* Public Key 생성 ( from 인증서 )
----
keytool -import -alias config-public-key -file config-public.cer -keystore config-public.jks -storepass 1234pass
----

* Config Server: public key
[source, yaml]
----
encrypt:
  key-store:
    location: classpath:/config-public.jks
    alias: config-server-key
    password: 1234pass
    secret: 1234pass
----

* Config Client: private key
[source, yaml]
----
encrypt:
  key-store:
    location: classpath:/config-private.jks
    alias: config-private-key
    password: pass1234
    secret: pass1234
----

== Refs
https://docs.spring.io/spring-cloud-config/docs/current/reference/html/
https://spring.io/guides/gs/centralized-configuration/
https://www.baeldung.com/spring-cloud-configuration#Encryption