
logging:
  level:
    jhkim105.tutorials: debug
#    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
#    org.hibernate.type.EnumType: trace
#    org.springframework.transaction: debug
    org.hibernate.cache: debug
    org.ehcache: debug

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mariadb://localhost/demo_jpa_cache?createDatabaseIfNotExist=true
    username: root
    password: 111111
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        id.new_generator_mappings: false
        javax.cache.missing_cache_strategy: fail
        cache:
          use_second_level_cache: true
          redisson:
            fallback: true
            config: redisson.yml
            user:
              eviction.max_entries: 2000
              expiration.time_to_live: 1000
              expiration.max_idle_time: 1000


    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always