# Create tenant
POST http://localhost:8080/tenants/create
Content-Type: application/x-www-form-urlencoded

name=tenant999


> {%
client.global.set("tenantId", response.body.id);
%}

###

# Delete tenant
POST http://localhost:8080/tenants/delete
Content-Type: application/x-www-form-urlencoded

name=tenant999

###
# Drop tenant database
POST http://localhost:8080/tenants/drop
Content-Type: application/x-www-form-urlencoded

name=tenant999

###