# Create tenant
POST http://localhost:8080/tenants/create
Content-Type: application/x-www-form-urlencoded

name=tenant999


> {%
client.global.set("tenantId", response.body.id);
%}

###

# Create User
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "username4",
  "tenantId": "{{tenantId}}"
}

> {%
client.global.set("userId", response.body.id);
client.log(client.global.get("userId"));
%}

###

# Update User
POST http://localhost:8080/users
Content-Type: application/json

{
  "id": "{{userId}}",
  "username": "username12",
  "tenantId": "{{tenantId}}"
}

###

# Get Users
GET http://localhost:8080/users?tenantId={{tenantId}}

###

# Update Username
POST http://localhost:8080/users/{{userId}}/username
Content-Type: application/x-www-form-urlencoded

username=username000_&tenantId={{tenantId}}

###
