app:
  config-name: native-config-client-development
  config-password: '{cipher}AQATf2+BOJ1ViTLhdCGMy/eznTeCLlehguTVXkdxkT/Mldd73hDQMX72I41pQgLyl9AB9Su/W0hMD2HAiVR/hKb6J4RCY4NA9kQ+Adzy5WWGKsoYLUyEejqfQYBl6VgVPwwZ8LU8p5nigjgk9lEHA/SQEOjGbaCNiaUHbOkN+SwkvI6dkHF2+SPYPzO/0IYDF0EDydtGmUUlU21orUolFpj8wSXaYoQS7YkCkQPwNmgUnRPjnXgn605QUC7Cdkx0ZMEZw8UdMs3/Lq1g1YG9C9zqxTvYxxOzVT+NFQmUiperyUIH1evjL4JgkuAoPcVUtaOOzQ4KiAzplbjo3fR4BdmxL+kfsx1jZK2HMY1xBywInKFG1Gr6ZyYkTNCfGvkcTiQ'

