logging.level:
  'jhkim105.tutorials': debug
server:
  port: 8081
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/demo
          jwk-set-uri: http://localhost:8089/realms/demo/protocol/openid-connect/certs