logging:
  level:
    org.springframework.cloud.gateway: trace

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: book
          uri: http://localhost:8081
          predicates:
            - Path=/books
        - id: rating
          uri: http://localhost:8082
          predicates:
            - Path=/ratings

