server:
  port: 8081
spring:
  config:
    import: 'optional:configserver:'
  application:
    name: product-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/demo
          jwk-set-uri: http://localhost:8089/realms/demo/protocol/openid-connect/certs
  sleuth:
    sampler:
      probability: 1.0

#  zipkin:
#    service:
#      name: product

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true