
spring:
  rabbitmq:
    host: localhost
    port: 5672
  jmx:
    enabled: true
logging:
  level:
    com.example: debug


mqtt:
  broker-url: tcp://localhost:1883
  #  broker-url: tcp://devpns.remotemeeting.com:1883
  qos: 2
  async: true
  completion-timeout: 5000