logging.level:
  "org.springframework.security": trace
spring:
  datasource:
    url: jdbc:mariadb://localhost/demo_security?createDatabaseIfNotExist=true
    username: root
    password: 111111
  sql:
    init:
      mode: always
      continue-on-error: false
  #      data-locations: data.sql
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    properties:
      hibernate:
        'hbm2ddl.auto': create
        'id.new_generator_mappings': false