server:
  address: 0.0.0.0
  port: 8081
#  compression:
#    enabled: true
#    mime-types:
#    excluded-user-agents:
logging:
  level:
    'jhkim105.tutorials': debug
app:
  storage-path: @project.basedir@/storage
  resource-mappings:
    files:
      path: /files/**
      locations: file:${app.storage-path}/files/, file:${app.storage-path}/files2/
