logging:
  level:
    "com.example": trace
    "org.hibernate.SQL": debug
    "org.hibernate.type.descriptor.sql.BasicBinder": trace
spring:
  datasource:
    url: jdbc:mariadb://localhost/demo?createDatabaseIfNotExist=true
    username: root
    password: 111111
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
application:
  database-encrypt-type: JASYPT
  database-encrypt-password: secret#01