# LOGGING
logging:
  level:
    jhkim105.tutorials: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.EnumType: trace

spring:

  # DB - MySQL
  datasource:
    url: jdbc:mariadb://localhost/demo_envers?createDatabaseIfNotExist=true
    username: root
    password: 111111

  sql:
    init:
      mode: always
#      data-locations: data.sql
      continue-on-error: false

  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    properties:
      hibernate.id.new_generator_mappings: false
#      org.hibernate.envers.audit_table_suffix: _h
#      org.hibernate.envers.store_data_at_delete: true
#      org.hibernate.envers.global_with_modified_flag: true
#      org.hibernate.envers.modified_flag_suffix: _mod
  data:
    rest:
#      basePath: /data
      detection-strategy: annotated
