
# LOGGING
logging:
  level:
    root: warn
    'jhkim105.tutorials': debug
    'org.hibernate': info
    'org.hibernate.SQL': debug
    'org.hibernate.type.descriptor.sql.BasicBinder': trace
    'org.hibernate.type.EnumType': trace
    'org.springframework.transaction': trace
    'org.springframework.orm.jpa': debug
    'org.springframework.jdbc.core': trace
spring:
  datasource:
    url: jdbc:mariadb://localhost/demo_jpa?createDatabaseIfNotExist=true&profileSQL=true
    username: root
    password: 111111
  sql:
    init:
      mode: always
      continue-on-error: false
  #      data-locations: data.sql
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    properties:
      'hibernate.id.new_generator_mappings': false
      'hibernate.generate_statistics': true
      'hibernate.session.events.log.LOG_QUERIES_SLOWER_THAN_MS': 1