
# LOGGING
logging:
  level:
    jhkim105.tutorials: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.EnumType: trace
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: @db.url@
    username: @db.username@
    password: @db.password@
  sql:
    init:
      mode: always
      continue-on-error: false
  #      data-locations: data.sql
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    properties:
      hibernate.id.new_generator_mappings: false