# curl -X POST http://localhost:8081/oauth/token -u "client01:secret01" -H "Content-type: application/x-www-form-urlencoded" -d grant_type=password -d scope=read -d username=user01 -d password=pass01
POST http://localhost:8081/oauth/token
Authorization: Basic client01 secret01
Content-Type: application/x-www-form-urlencoded

grant_type=password&scope=read&username=user01&password=pass01

> {%
client.global.set("accessToken", response.body.access_token);
client.global.set("refreshToken", response.body.refresh_token);
%}
###

# token key
# curl http://client01:secret01@localhost:8081/oauth/token_key
GET http://client01:secret01@localhost:8081/oauth/token_key
###

# grant_type=client_credentials
# curl "http://localhost:8081/oauth/token" -u "client01:secret01" -d "grant_type=client_credentials&scope=read"
POST http://localhost:8081/oauth/token
Authorization: Basic client01 secret01
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials

> {%
client.global.set("accessToken", response.body.access_token);
%}
###

# curl -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MDY3MDM5MzEsInVzZXJfbmFtZSI6InVzZXIiLCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwianRpIjoiNzU4ZjQ5ZTEtN2UyOC00ZTc0LThmZjgtMTQwNDVmM2NmZGRmIiwiY2xpZW50X2lkIjoiZm9vIiwic2NvcGUiOlsicmVhZCJdfQ.x3SHVWF5EOQRxAsUmwXyjJx9aSqnniuFFGYHSACeJ2o " "http://localhost:8080/users"
GET http://localhost:8082/posts
Authorization: Bearer {{accessToken}}

###







